export const SEED_ASSETS = [
  // GUITARS
  {asset_id:"G001",category:"GUITARS",category_label:"Guitars",make:"Gretsch",model:"G6128T Duo Jet",description:"Electric, black finish, Bigsby B6, dual humbuckers",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"G002",category:"GUITARS",category_label:"Guitars",make:"Squier",model:"Stratocaster",description:"Electric, mint green",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"G003",category:"GUITARS",category_label:"Guitars",make:"Peavey",model:"Raptor Plus EXP",description:"Electric, HSS, candy apple red, bolt-on maple neck",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"G004",category:"GUITARS",category_label:"Guitars",make:"Takamine",model:"KC70",description:"Kenny Chesney Signature, OM acoustic-electric, solid cedar top, solid sapele back/sides, CT4B II preamp, handcrafted Japan Oct 2007",serial:"07101034",status:"active",condition:"excellent"},
  {asset_id:"G005",category:"GUITARS",category_label:"Guitars",make:"Martin",model:"LXE1",description:"Little Martin, X-Series, HPL spruce top, Fishman Sonitone, 23in scale",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"G006",category:"GUITARS",category_label:"Guitars",make:"Loog",model:"Mini Acoustic",description:"3-string acoustic, red, 15in scale",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"G007",category:"GUITARS",category_label:"Guitars",make:"Guild",model:"12-String",description:"1975 vintage acoustic 12-string, USA",serial:"TBD",status:"active",condition:"fair"},
  {asset_id:"G008",category:"GUITARS",category_label:"Guitars",make:"Washburn",model:"Acoustic Bass",description:"Acoustic bass",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"G009",category:"GUITARS",category_label:"Guitars",make:"Unknown",model:"Headless Bass",description:"Black headless electric bass, Steinberger-style",serial:"TBD",status:"active",condition:"fair"},
  // AMPLIFIERS
  {asset_id:"A001",category:"AMPLIFIERS",category_label:"Amplifiers",make:"Rivera",model:"Pubster 25",description:"25W all-tube guitar combo, 3-band EQ, effects loop",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"A002",category:"AMPLIFIERS",category_label:"Amplifiers",make:"Rivera",model:"FS-20",description:"Footswitch for Rivera amps",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"A003",category:"AMPLIFIERS",category_label:"Amplifiers",make:"Vox",model:"MV50 AC Set",description:"50W hybrid tube head (Nutube 6P1) + BC108 1x8in cabinet",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"A004",category:"AMPLIFIERS",category_label:"Amplifiers",make:"Fender",model:"Mustang IV",description:"150W 2x12in modeling combo, 100+ presets, USB",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"A005",category:"AMPLIFIERS",category_label:"Amplifiers",make:"Fender",model:"Acoustic Junior GO",description:"100W battery-powered acoustic combo, Bluetooth, USB recording",serial:"TBD",status:"active",condition:"excellent"},
  // SYNTHESIZERS
  {asset_id:"S001",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Access",model:"Virus TI2 Polar (Dark Star)",description:"Virtual analog, 4-part multitimbral, 80 voices, USB audio/MIDI",serial:"EPERUfmBtCA",status:"active",condition:"excellent"},
  {asset_id:"S002",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Moog",model:"Sub 37 Tribute Edition",description:"Analog paraphonic, Ladder filter, 37-key, arpeggiator, sequencer",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S003",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Moog",model:"Mother-32 #1",description:"Semi-modular, Ladder filter, 32-step sequencer. In 4-tier rack",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S004",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Moog",model:"Mother-32 #2",description:"Semi-modular, Ladder filter, 32-step sequencer. In 4-tier rack",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S005",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Moog",model:"DFAM",description:"Drummer From Another Mother, semi-modular percussion. In 4-tier rack",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S006",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Moog",model:"Subharmonicon",description:"Semi-modular polyrhythmic, 2 sequencers. In 4-tier rack",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S007",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Moog",model:"4-Channel Mixer",description:"4-in stereo mixer, Sound Studio bundle. In 4-tier rack",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S008",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Behringer",model:"2600 Blue Marvin",description:"ARP 2600 clone, 3 VCOs, spring reverb, 93 patch points",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S009",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Erica Synths",model:"Pico System III",description:"Desktop modular, 13 Pico modules, West/East Coast hybrid",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S010",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Erica Synths",model:"Black System III",description:"Full Eurorack modular performance system, Black series",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S011",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Roland",model:"SH-4d",description:"Compact desktop, 4-part multitimbral, 11 OSC models, USB audio",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"S012",category:"SYNTHESIZERS",category_label:"Synthesizers",make:"Korg",model:"MS2000R",description:"Virtual analog rack, 4-voice, MMF-2 filter, vocoder. Made in Japan",serial:"008246",status:"active",condition:"good"},
  // CAMERAS
  {asset_id:"CAM001",category:"CAMERAS",category_label:"Cameras",make:"Canon",model:"EOS R5",description:"45MP full-frame mirrorless, 8K RAW video, IBIS, CFexpress/SD",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"CAM002",category:"CAMERAS",category_label:"Cameras",make:"Canon",model:"EOS R6 Mark II",description:"24.2MP full-frame mirrorless, 40fps, 6K RAW crop, IBIS",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"CAM003",category:"CAMERAS",category_label:"Cameras",make:"Canon",model:"EOS 5D Mark III",description:"22.3MP full-frame DSLR, dual card CF/SD, 61-point AF",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"CAM004",category:"CAMERAS",category_label:"Cameras",make:"Canon",model:"EOS 5D Mark IV",description:"30.4MP full-frame DSLR, Dual Pixel AF, 4K video, GPS",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"CAM008",category:"CAMERAS",category_label:"Cameras",make:"Sony",model:"FX3",description:"Full-frame cinema, 4K 120fps, S-Log3, XLR top handle",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"CAM013",category:"CAMERAS",category_label:"Cameras",make:"Matterport",model:"Pro2",description:"3D camera, 134MP, WiFi, photogrammetry + structured light",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"CAM015",category:"CAMERAS",category_label:"Cameras",make:"Blackmagic",model:"Pocket Cinema Camera 6K G2",description:"6K Super 35, L-mount, 13 stops DR, RAW/BRAW, CFast/SD",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"CAM016",category:"CAMERAS",category_label:"Cameras",make:"DJI",model:"Mini 3 Pro",description:"249g drone, 4K 60fps, tri-directional obstacle sensing",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"CAM017",category:"CAMERAS",category_label:"Cameras",make:"DJI",model:"Air 2S",description:"1in CMOS drone, 5.4K 30fps, obstacle sensing 4 directions",serial:"TBD",status:"active",condition:"excellent"},
  // MICROPHONES
  {asset_id:"MIC001",category:"MICROPHONES",category_label:"Microphones",make:"Neumann",model:"TLM 103",description:"Large-diaphragm condenser, cardioid, transformerless, 48V phantom",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"MIC002",category:"MICROPHONES",category_label:"Microphones",make:"AKG",model:"C414 XLII",description:"Large-diaphragm condenser, 9 polar patterns, gold-sputtered capsule",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"MIC003",category:"MICROPHONES",category_label:"Microphones",make:"Shure",model:"SM7B",description:"Dynamic cardioid broadcast mic, flat/presence EQ, hum rejection",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"MIC004",category:"MICROPHONES",category_label:"Microphones",make:"Shure",model:"SM57",description:"Instrument dynamic cardioid, industry standard",serial:"TBD",status:"active",condition:"good"},
  {asset_id:"MIC022",category:"MICROPHONES",category_label:"Microphones",make:"Electro-Voice",model:"RE20",description:"Cardioid dynamic broadcast, Variable-D, internal pop filter",serial:"TBD",status:"active",condition:"excellent"},
  // MIXERS
  {asset_id:"MI001",category:"MIXERS_AND_INTERFACES",category_label:"Mixers & Interfaces",make:"Neve",model:"8816 Summing Mixer",description:"16-channel analog summing mixer, Neve transformer on master",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"MI003",category:"MIXERS_AND_INTERFACES",category_label:"Mixers & Interfaces",make:"Focusrite",model:"Scarlett 18i20 Gen 3",description:"18-in/20-out USB, 8 preamps, ADAT, S/PDIF",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"MI010",category:"MIXERS_AND_INTERFACES",category_label:"Mixers & Interfaces",make:"Behringer",model:"X32 Rack",description:"40-in/25-out digital rack mixer, 32 preamps, USB recording",serial:"TBD",status:"active",condition:"excellent"},
  // MONITORS
  {asset_id:"MON001",category:"STUDIO_MONITORS",category_label:"Studio Monitors",make:"Yamaha",model:"HS8",description:"8in powered studio monitor, 120W, bi-amp, XLR/TRS",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"MON002",category:"STUDIO_MONITORS",category_label:"Studio Monitors",make:"Yamaha",model:"HS8 #2",description:"Second HS8 of stereo pair",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"MON003",category:"STUDIO_MONITORS",category_label:"Studio Monitors",make:"Yamaha",model:"HS8S",description:"8in powered subwoofer, 150W, LPF, phase invert",serial:"TBD",status:"active",condition:"excellent"},
  // EFFECTS
  {asset_id:"FX001",category:"EFFECTS",category_label:"Effects",make:"Line 6",model:"Helix Floor",description:"Guitar/bass multi-effects, HX modeling, 12 expression inputs, MIDI",serial:"TBD",status:"active",condition:"excellent"},
  {asset_id:"FX008",category:"EFFECTS",category_label:"Effects",make:"Eventide",model:"H9000",description:"Rackmount multi-effects, 16 DSPs, 4 independent engines, USB",serial:"TBD",status:"active",condition:"excellent"},
  // SOFTWARE
  {asset_id:"SW001",category:"SOFTWARE",category_label:"Software",make:"Apple",model:"Logic Pro X",description:"DAW. Used with Euphonix MC Mix + MC Control",serial:"N/A",status:"licensed",condition:"excellent"},
  {asset_id:"SW002",category:"SOFTWARE",category_label:"Software",make:"Apple",model:"Final Cut Pro X",description:"Video editor. Used with MOTU HD Express",serial:"N/A",status:"licensed",condition:"excellent"},
  {asset_id:"SW005",category:"SOFTWARE",category_label:"Software",make:"Native Instruments",model:"Komplete 14 Collectors Edition",description:"Top-tier NI production bundle, all instruments + effects",serial:"N/A",status:"licensed",condition:"excellent"},
]
